services:
  backend:
    build:
      context: ./backend
    container_name: symfony_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assurance_pro
    ports:
      - "3307:3306"