name: Symfony Tests

on:
  push:
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo_mysql

      - name: Install Composer dependencies
        run: composer install

      - name: Symfony Check
        run: php bin/console --version